author: Ribesg
main: ${project.groupId}.${project.name}
name: ${project.name}
description: ${project.description}
url: ${project.url}
version: ${project.version}

# load: POSTWORLD

commands:
  glow:
    description: Toggle glow on held item
    default: true
